### ISSUE TITLE
Discussion about goals

### ISSUE THREAD

**Issue by LucianoBestia** [LucianoBestia/cargo_crev_web#1]
I believe that cargo-crev reviews mean different things to different people.
For me I imagine this web app to inform the developer about a crate before they choose to use it in their project. This step is now missing in the eco-system. And I think it is a critical step when building a project. If you start with the wrong dependency is very hard to change it later. So my 2 primary questions are:
1. is this author and crate trusted. I want to avoid malware inside libraries. Supply chain attack.
2. How compares this library with alternatives. What are the pro and cons relative to alternatives: developer friendly, maintained, sensible API, performance, good coding style that enables others to add or modify the code. No misteries !
Advisories and issues are useful to see the reaction of the maintainer and how quick they solve security problems. And enable devs to avoid certain versions of that crate.
For me I would compare it with reviews in booking.com or amazon. I always read that reviews before buying to get a more realistic picture of the product. Because the author will always say the best for his product. But the user will be more truthfull. The user dont need to be a professional in the field to have his opinion. Sure the opinion of a prodigy coder is more appreciated, but also average coders can critique a crate. If there are enough reviews the truth will come out. It can be different for different people. There can be also scams, but they cannot be long lived.

**Comment by dpc** [comment]
Subscribed.
