### ISSUE TITLE
Logo and name

### ISSUE THREAD

**Issue by LucianoBestia** [LucianoBestia/cargo_crev_web#10]
I gave the working name to my project "cargo_crev_web". 
But it does not sound good for the users.
We should find something better.
It will be used for the web sub-directory, title on every page and people will use this name.
cargo-crev looks also like a working name. 
I would like to have the word Rust in the name and crev.
Maybe `Rust code creviews` ?  
It is a funny game with words. This helps with uniqueness in search machines.
`https://web.crev.dev/rust-creviews/` sounds very good.
@dpc, Look at the experiment with the logo:
https://web.crev.dev/rust-creviews/

![image](https://user-images.githubusercontent.com/31509965/83490046-f2ae1500-a4cc-11ea-8af0-1cb62582e4f7.png)

**Comment by dpc** [comment]
I don't know what to think about "creviews". :laughing: 

You already have `web` and `crev` in the domain name. :) . `/rust/reviews` `/rust/authors` etc would work I think. Or `/reviews/rust` `/authors/rust` etc.

Canonically Crev package is identified by  (in order):

* source (https://crates.io, or custom package registry url, or something else for other languages)
* name
* version

So `<source>/<name>` fits and can always be extended to `<source>/<name>/<version>` if the user want to details of particular version or something.

**Comment by LucianoBestia** [comment]
hahaha I like things to be a little bit funny. 😆
"creviews" looks like a "review" with a typing mistake. Sure it looks very much like "crev".
I think it is funny and interesting and unique for easy searching. New people will clearly understand it is about reviews. For them "crev" in not enough similar to "review". Once they learn it, crev is totally enough.
I was thinking about the sub-directory name:
First I thought to use /rust-reviews/, but it was too serious and not catchy at all.
Then I thought about /rust/. This is too short. It looks good on your domain name, but I have a plan...
Please read my plan on this other issue: 
https://github.com/LucianoBestia/cargo_crev_web/issues/13
So I like the most /rust-creviews/. 
I need your approval for this sub-dir name. I don't think other people should be involved. 
Of course if you really don't like it, we continue to search for a better sub-dir name.

**Comment by dpc** [comment]
I guess `creview` is kind of ... unique and thus makes searches a bit easier. Not exactly funny, I guess. But Googability is important so ... maybe... it's a good idea?

I'd do `/creviews/crates.io/...` . For good or bad, [that's what is being put in the proof itself](https://github.com/dpc/crev-proofs/blob/c324d06567368b03cc89c659723b3729cf083a96/FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE/reviews/2018-12-packages-Ua7DxQ.proof.crev#L9) for packages from crates.io. Even for Rust, we're hopping to support alternative registries, so it doesn't even identifies a language itself, but the namespace withing which the package name is unique.

> I need your approval for this sub-dir name.

You don't need my approval. :D . I consider this project under your authority, and I'm just giving you my opinions. If you go with anything else, it's totally fine with me. My opinions are sometimes completely wrong.

**Comment by LucianoBestia** [comment]
"There are two hard things in computer science: naming things, cache invalidation,  and off-by-one errors."  :-D

The name of the language Rust is not really a good pick. If I search on google I got a lot of Rust the game or rust "the oxidizing of steel" articles. Why not Ruust or Reust or something more unique. There exists "rust-lang", but is long forgotten and nobody really use it.
Cargo? what is that name? At least RustCargo or Rustgo. Nobody can never intuitively put together Rust and Cargo.
Crate? why that? it is not unique enough and is completely unrelated to rust. Maybe it has some meaning together with cargo. 
So of all this names only "Rust" has some true meaning. Not 100% good, but the best we have.
I don't want to use Cargo or Crate. neither crates.io.
"Creviews" was a moonshot, but it is not great. "crev" + "review" words are enough.
I appreciate your words and opinion and I concluded to use:
<https://web.crev.dev/rust-reviews/>
or 
<http://localhost/rust-reviews/ >

I think it is good to split crev reviews by language. This is what interests developers. The source is not important. If I know the language I can make UI specifically for that language. For example I put cargo commands, links to documentation, crates.io, lib.rs. That is not possible if the site is generic for every language. I know also the structure of cargo.toml and how dependencies work. So it can be an efficient Rust only world.
I will change the name now and I hope it will good for a long time :-)
Thanks.

**Comment by LucianoBestia** [comment]
@dpc, Try it:
https://web.crev.dev/
Do you want to say something more on the first page? 
This will be the root page for accessing different languages.
Here is now only a link to `rust-reviews`.

Are you ok with the logo I used?
This is all possible to change anytime.

**Comment by dpc** [comment]
Just to make sure you know: You can have two completely unreleated crates named `foo`, hosted on multiple different crate-registries. crates.io is just the default, built-in registry, but if there was ever any ecosystem split or whatever (like npm, yarn, etc. in JS-world) it would become a little problem. Usually different crate registries are meants for companies to host private crates, but nothing is stopping these from hosting public crates as well.

I don't like this "Open this link: https://web.crev.dev/rust-reviews/" on the main page. If that's what I should click, why not just redirect me? I'm too lazy to click stuff. :D

Other than that looks OK. The usability could be improved with some `Search..." input here and there, etc. but good enough so far for me, especially for usage like Badges.

**Comment by LucianoBestia** [comment]
I improved the first language agnostic page:
<https://web.crev.dev/>
and the second Rust specific page with a "legend" to explain the cryptic column names:
<https://web.crev.dev/rust-reviews/>

My first thought was that everybody  will come to this webpage through crates.io or lib.rs or VSCode extension. Than they go straight to the crate and don't even see the first page.
That is true for developers that already know about crev.
But I realize now that this web pages (first and second) will be the entry point for new developers. And if they like what they see, they will start to learn about crev and eventually use it.
I will try to make something appealing, but this is not my talent. I will need some help with texts and images to make it beautiful ;-)

**Comment by LucianoBestia** [comment]
I found today the logo with spectacles.
@dpc, Would you prefer to use this logo?
Instead of the shield logo.

![image](https://user-images.githubusercontent.com/31509965/84145076-e0a51700-aa76-11ea-9a21-5e7dc35ddbd7.png)
![image](https://user-images.githubusercontent.com/31509965/84145176-0c280180-aa77-11ea-883d-aa3092337de2.png)

**Comment by dpc** [comment]
The shield one logo is supposed to replace the quick spectacles logo that I've hat together in 5 minutes. https://github.com/crev-dev/cargo-crev/pull/347
