### ISSUE TITLE
XSS from reviews

### ISSUE THREAD

**Issue by chrysn** [LucianoBestia/cargo_crev_web#11]
Reviews can contain '<' characters (I use them in URIs like `as seen on <http://www.example.com/>.` to ensure proper URI delimiting). These are currently not escaped as evidenced by the blockhash section of [my review page](https://web.crev.dev/cargo_crev_web/author/bYdCa4xhd5VL4dlcVPBxV51PrW5joFp9U04rKgcTvk8/).

The safe behavior would be to escape HTML's magic characters (`<>&"`), or preferably to declare them as untrusted plain-text input (as opposed to trusted HTML input or untrusted HTML input that would go through sanitization) to the used HTML templating library.

In general, this kind of issue can lead to security vulnerabilities (cross-site scripting / XSS, eg. allowing attackers to steal a logged in user's credentials to the attacked site); I'm reporting it here publicly because in the current state of the project it seems not to be used in connection with any sensitive data (like logins), so the worst a malicious review can do is inject code like `<script>alert("Hello World!")</script>`.

**Comment by LucianoBestia** [comment]
Thank you very much. I missed that. Sure I must escape all the string. 
I just forgot. I will do it now.

**Comment by LucianoBestia** [comment]
Corrected. Thx
![image](https://user-images.githubusercontent.com/31509965/83511256-fef59a80-a4eb-11ea-8b69-f09affc09681.png)

I must also take care of the url encoding/decoding. I will check now. 
I will try to make an enum: strings with html encoding and strings with url encoding.
So I can check in the code that the wrong type does not come to the wrong function.
Just an idea. I don't know yet how to do it. But sounds like a good way to take advantage of the strong type check in compile time . Interesting.

**Comment by chrysn** [comment]
URL encoded strings shouldn't need any special processing in HTML. When a URI is passed into an HTML page's field, it should be HTML-escaped like any other text. (Especially URIs like `http://example.com/?a=1&b=2` typically need their `&` replaced).

Thanks for fixing this that quickly.
