### ISSUE TITLE
public repo with crates.io minimal data

### ISSUE THREAD

**Issue by LucianoBestia** [LucianoBestia/cargo_crev_web#16]
It would be nice to have a github repo with minimal data from crates.io index.
There already exists the repo 
https://github.com/rust-lang/crates.io-index
but it is far too much data.
Most of the applications need only this:
```json
{
    "crates": [
        {
        "name": "a1",
        "description": "This is a test crate. Thanks for coming my homepage."
        "versions": ["0.1.1"]
        "repo": "https://github.com/keonjeo/a1"
        },
        {
        "name": "num-traits",
        "description": "Numeric traits for generic mathematics",
        "versions": ["0.2.12","0.2.11","0.2.10","0.2.9","0.2.8","0.2.7","0.2.6",,"0.2.5","0.2.4","0.2.3","..."}]
        "repo":"https://github.com/rust-num/num-traits"
        },
        ...
    ]
}
```
The versions are limited to 10 last versions. The string "..." symbolize, there is more.
@kornelski, you probably pull the full data from  the repo crates.io-index for lib.rs on regular basis?
Can you run after fetch a small program to extract the minimal set of data to a special folder.
And then push that folder to a new repo on Github. 
Then every developer could fetch this data easily and use it in his application.
I need it for web.crev.dev.

**Comment by LucianoBestia** [comment]
@kornelski, The crates.io-index does not contain the crate "description".
Where do you find it ?

**Comment by kornelski** [comment]
I download crate tarballs, decompress them, and parse their cargo.toml

**Comment by LucianoBestia** [comment]
Wow. That is a lot of work. 
Could you export this data to a json file? And make it public through GitHub?

**Comment by LucianoBestia** [comment]
I suppose that the repository uri you get also from cargo.toml.

**Comment by LucianoBestia** [comment]
I wrote an issue also to crates.io developers, but I don't expect any movement there.
https://github.com/rust-lang/crates.io/issues/2574

**Comment by kornelski** [comment]
It is a bit of work, but it's not too hard. There's reqwest, flate2, tar, toml, and you just need to connect them together.

**Comment by LucianoBestia** [comment]
Do you use the "database dump"?
https://crates.io/data-access

**Comment by kornelski** [comment]
I use it, but only for downloads stats.

It has downsides:

* it's huge and slow to decompress
* it's delayed by 1 day, so it's missing newly published crates
