### ISSUE TITLE
announce to users.rust-lang.org

### ISSUE THREAD

**Issue by LucianoBestia** [LucianoBestia/cargo_crev_web#17]
I think it is time to announce it on users.rust-lang.org.
Yes, I am prepared to a thunderstorm of opinions.
But I believe in the cause and I think the web site is ok.
Let's evolve.
@dpc, @kornelski, Can you please, take a look before I make the announcement?

**Comment by kornelski** [comment]
I suspect the first feedback you'll get is people not understanding what it is at all.

- what's crev?
- what's up with the cryptic 1-letter headers?

And comments about visual style, like:

- the dark logo on dark background is unreadable
- geocities colors

**Comment by LucianoBestia** [comment]
Yes I expect a lot of opinions from people that will never use it. I dont care. I wait for people that will use it.
