### ISSUE TITLE
Official people

### ISSUE THREAD

**Issue by dtolnay** [LucianoBestia/cargo_crev_web#19]
Hi -- I noticed my name pop up in https://web.crev.dev/rust-reviews/people_of_rust/. From this list I can't tell what distinction is being made between "official people from rust-lang.org" and "other people". (This isn't me taking offense, since this list is ultimately up to you and your trust, just flagging the following): In particular brson and Centril are not currently on any team on rust-lang.org, and I'm officially a standard library maintainer since 2017 (https://www.rust-lang.org/governance/teams/library).

<p align="center"><img alt="screenshot" width="60%" src="https://user-images.githubusercontent.com/1940490/85095191-9245f580-b1a5-11ea-8f66-c17e1d2ce695.png"></p>

**Comment by LucianoBestia** [comment]
Thank you for correcting me. Actually I never met anyone and I appreciate the info. I will correct it now. Were brson and centril before in an official team? I will put them in "other". For me other means they were historically in a team, but not anymore. There is a lot of their work still around. I would like also some info what is the most important work of a member. Can you help me? For you I found thenserde project. Amazing. Thank you.

**Comment by LucianoBestia** [comment]
Do you think is funny "People of Rust"? Not exactly "men of steel".

**Comment by dtolnay** [comment]
"People of Rust" is the perfect phrase I think. I think it nicely captures the transitive trust by way of Rust project leadership.

> Were brson and centril before in an official team?

Yes exactly.

> I would like also some info what is the most important work of a member. Can you help me?

On your existing list, here are the people I know and trust:

- \[ David Tolnay - GitHub: dtolnay - **std, serde** \]
- Niko Matsakis - GitHub: nikomatsakis - **core, compiler**
- Alex Crichton - GitHub: alexcrichton - **std, cargo**
- Mark Rousskov - GitHub: Mark-Simulacrum - **core, infra, release**
- Nick Cameron - GitHub: nrc - **core, rustfmt**
- Pietro Albini - GitHub: pietroalbini - **core, infra**
- Steve Klabnik - GitHub: steveklabnik - **core, the book**
- Josh Triplett - GitHub: joshtriplett - **lang design**
- Without Boats - GitHub: withoutboats - **async**
- Carol Nichols - GitHub: carols10cents - **core, the book**
- Manish Goregaokar - GitHub: Manishearth - **core**
- Andrew Gallant - GitHub: BurntSushi - **std, ripgrep**
- Nick Fitzgerald - GitHub: fitzgen - **webassembly**
- Tony Arcieri - GitHub: tarcieri - **secure code**
- Andre Bogus - GitHub: llogiq - **moderation**<br><hr>
- Brian Anderson - GitHub: brson - **early core, compiler, std**
- Mazdak Farrokhzad - GitHub: Centril - **lang design**

The remaining one I don't know or trust (17cupsofcoffee).

**Comment by dtolnay** [comment]
If this isn't overstepping (feel free to ignore if it is), here are the other people that I consider "People of Rust" i.e. positions of *substantial* trust by the Rust team:

- Felix Klock - GitHub: pnkfelix - **compiler, lang design**
- Ralf Jung - GitHub: RalfJung - **unsafe code**
- Aidan Hobson Sayers - GitHub: aidanhs - **core, infra**
- Ashley Williams - GitHub: ashleygwilliams - **core**

There are other people I trust obviously, but the above are the ones I think are glaringly missing.

**Comment by LucianoBestia** [comment]
Thank you. Your help is welcome.

I am also working on a new serialization format `qvs20` similar to `csv`. 
https://github.com/LucianoBestia/QVS20
When you have time, could you please give it a look. I hope it will be interesting to you.
I will need a lot of time to make something useful, but the idea is worth it.
The final goal is of course to make it work with serde. Thx.

**Comment by dtolnay** [comment]
Thanks for the updates!
