### ISSUE TITLE
use long term domain "crev.dev" for website

### ISSUE THREAD

**Issue by LucianoBestia** [LucianoBestia/cargo_crev_web#2]
The beta version of the web app is now on my developer domain `bestia.dev`.
The web app is already usable. It will only confuse users if we change the domain later.
It would be better to use the `crev.dev` domain of @dpc (the author of crev) from the start.
I suggest this url:
https://crev.dev/cargo_crev_web/
I am happy to see `lib.rs` of @Kornelski to have a similar approach for cargo-crev.
But I believe crev and cargo-crev should have a standalone domain.
The webserver can run anywhere, but the domain should be stable and fixed for long term.

This is how I registered/setup my domain on <https://porkbun.com/> for example:
The ip number is from my google vm Compute Engine and can be used for `crev.dev` too.
Till the traffic is small it can run on my tiny micro server ( f1-micro, 0.2 virtual CPU, 0.60GB RAM).
![image](https://user-images.githubusercontent.com/31509965/83380084-adb9ae00-a3fa-11ea-954a-9c41f4ce8070.png)

**Comment by LucianoBestia** [comment]
Past conversation on this topic :
https://github.com/crev-dev/cargo-crev/issues/334

**Comment by dpc** [comment]
![Screenshot from 2020-06-01 13-41-08](https://user-images.githubusercontent.com/9209/83452569-ced7ca00-a40d-11ea-8059-c7a8fa6eaefd.png)

**Comment by dpc** [comment]
One thing that bother me a little bit is that crev is ecosystem independent (we have WIP on Python and Node frontends), and right now the UI is targeting only Rust, which might be confusing. We could either do `rust.web.crev.dev` or `web.crev.dev/rust` or something like that, so it is possible to add support for other ecosystems without breaking the existing links.

**Comment by kornelski** [comment]
If other implementations use the same format of proof repository, then crev-lib could just support all ecosystems. The UI may just need to add filtering by language (crate source).

**Comment by dpc** [comment]
`crev-lib` should support arbitrary sources already, and I think it wouldn't be difficult for any frontend/UI to support multiple languages/ecosystems.

**Comment by LucianoBestia** [comment]
I don't have experience with other languages. 
I purposefully put the name `cargo` in `cargo_crev_web`.
So I can  focus on the Rust ecosystem and introduce cargo/rust exclusive functionality.
This would break for other languages. 
I would like to keep it separate. It is not difficult later when things stabilize to extract the common code and to generalize it. 
But it is very difficult to do that in the beginning without any prior experience.

**Comment by dpc** [comment]
So what domain should we use? `web-rust.crev.dev`?

**Comment by LucianoBestia** [comment]
I use a fixed sub-directory for the web-app because I have difficulties with relative routes.
This solves the problem of routes with trailing backslash or without.
A relative link from this 2 seemingly equal routes is completely different. 
https://github.com/seanmonstar/warp/issues/584
With a fixed sub-directory I can always start a link from the website root. 
I don't need to know the website name. 
I know it is not fantastic. But is simple.
Without a fixed sub-directory I would need to make every link to be calculated dynamically.
And probably a setting to store the basic route.
On my computer it could be `/cargo_crev_web/` on another `/rust/` or `/some/folder/rust/`.
Doable.

**Comment by LucianoBestia** [comment]
It's alive !
https://web.crev.dev/cargo_crev_web/crate/num-traits/
![image](https://user-images.githubusercontent.com/31509965/83466290-43554c00-a494-11ea-9823-b69c9f6b522f.png)

**Comment by dpc** [comment]
I don't understand the problems with urls you have. The link to the root of the namespace is just `<a href='/' ...` . I've been using `warp` for my own stuff and I do know that `a` and `a/` is not the same, but I don't see how it's a problem. :)

**Comment by dpc** [comment]
Would be better to shorter this url. :) http://web.crev.dev/cargo/num-traits would be enough.

**Comment by dpc** [comment]
BTW. You should post on r/rust soon. :)

I haven't looked under the hood, but make sure you do some caching here and there, or you might get surprised how quickly this can get killed. In particular the badges - couple of projects will add the to their github README, then get on top of HackerNews and if you don't server them from memory the service will die rather quickly.

Also think about it from the perspective of any unbound hosting costs. If your hosting charges you per GB of data sent or something, you might be surprised how quickly these can spike sometimes.

I've found some time to explore the website better. It does feel still like an early WIP, but it is very promising. 

It is very information dense, and even though I'm the original author of `cargo-crev` I scratch my head quite often about what is what. I think the general vision needs to be figured out first. Should it work somewhat like `crates.io` etc.? Have some top-level navigation between different functionalities (like badges vs reviews, etc)?

Anyway. Just some thoughts. Great job!

**Comment by LucianoBestia** [comment]
> Would be better to shorter this url. :) http://web.crev.dev/cargo/num-traits would be enough.
I wanted to leave space for other languages or web apps. With a dedicated sub-directory you can totally split them. Easy,
It is also possible to do it with subdomains, but it is a little bit more involving.
It is a matter of taste. 
I as a developer, like to have my web app isolated from the others in a sub-directory.

**Comment by LucianoBestia** [comment]
Caching is a priority.
On starting the server  I read all the files and create an Arc Mutex vector.
This is my index. It does not have the long text, mostly numbers. 
It is reindexed also after a scheduled fetch for new reviews every hour.
I always query the index first. It is in memory. Very small, fast. It is easy to group by, sum, count,...
Only when I need the whole review text I go read the files.
But first I go into the index to find exactly the file names and review unique key.
That way I read only the files that have the reviews and none other.
Very small quantity. I hope it will work.

**Comment by LucianoBestia** [comment]
I could cache the last 100 badges and return them from cache. That is clever.
Also invalidating the cache is straightforward. 
Every hour after the fetch and re-index I clear the cache and start again. Because the data may change. 
For badges I query only the index. Super fast in memory.

**Comment by LucianoBestia** [comment]
>Should it work somewhat like `crates.io` etc.? Have some top-level navigation between different
>functionalities (like badges vs reviews, etc)?

I imagine only one functionality for now:
a developer wants to add a crate in cargo.toml. He first goes to see the reviews.
Maybe there is something scatchy or a better alternative.
I don't imagine any other use. 
Sure, for us involved in the project we like to see numbers, trends, how people use it. But for the normal developer it is completely uninteresting.
Badges are nice because they are a link and good looking.
