### ISSUE TITLE
Make it easy to get reviews for deps as well?

### ISSUE THREAD

**Issue by icefoxen** [LucianoBestia/cargo_crev_web#20]
First off, thank you!  I've been wanting something like this for `crev` for a while, just never gotten around to making it.  

If you're looking at a review for a crate, say [`rand`](https://web.crev.dev/rust-reviews/crate/rand/), it would be nice to at least have a list of its dependencies with review summaries attached, similar to how the CLI tool does it.  I do know that getting full deps for each version of a particular crate is a Nontrivial Problem though, so I'd consider a best-effort solution to be fine.  Want a PR if I ever have time, or are you already working on something like this?

**Comment by LucianoBestia** [comment]
This is good idea.
For now I use only the crev-repos. They contain only reviews and trusted people.
It is not a monolith database. Every developer has his repo published publicly. I fetch them all and then scan them to put all data in one place.
The data for dependencies is not in this "database". 
It is in the crates-index repo, a beast to fetch and process on my micro server. 
But I will think about it.
My first step is to use "crates.io database dump" to make something small and usable.
Thanks

**Comment by icefoxen** [comment]
Yeah I sympathize with how much work it takes to process all of crates.io.  I have done it myself by starting from the git repo and scraping the API, it took days to do even with a fast server and fast internet.  The code for it is [here](https://hg.sr.ht/~icefox/cargofox/) but it's about a year old so I don't know if it's at all useful anymore.  

If it would be helpful for your development to have more computing power, I'd be happy to help, either by giving you a temporary account on one of the machines I administer or by buying you some VPS time.  I don't have time for Yet Another Programming Project but I feel like this tool is important and would like to help it succeed.  :-)

**Comment by LucianoBestia** [comment]
Great. Thank you very much.
Indeed I will need a machine with a little more power and more bandwidth to download daily 230 MB of database dump. Then I will transform it into something small and usable. And then other developers can download it very easy. Including also the Rust-reviews project.
This will make the info on the site much more complete and usable.
I plan to push the "small database" to GitHub so other projects can fetch it daily.
And I plan a small API for fast querying of small responses. 
The api of crates.io is practically unusable. I will stay in touch. 
I am working on the database extract_and_save now.

**Comment by icefoxen** [comment]
Ok, there's a couple option for machines.  

 * First: I can just give you a shell account on a Linode VPS which is always on and very reliable, but only has 2 cores, 4 GB of RAM and ~20 GB of free hard drive space.  There's a couple other users with shell accounts and I'd prefer to give you access to this one since I pay more attention to making sure it works well.
 * Second: there's a Ryzen 2400G system sitting under a table in my living room, which is a lot more powerful with 8 GB of RAM and a TB of hard drive space and still has pretty fast internet.  However, it occasionally gets turned off if I need to move furniture/cabling around, and sometimes the power goes off during a thunder storm.  If you need this much power, I'd prefer if we could set it up to just run a daily cron job or something that uploads the small-and-usable data somewhere instead of giving you shell access.
 * Third: I can paypal you 100 USD or so as a one-time donation to buy more VPS time/hardware yourself.

Email me at icefox@dreamquest.io when you have a decision and want to start setting it up!

**Comment by LucianoBestia** [comment]
Thank you. I will need very little power. So the first Linode VPS sound perfect.
