### ISSUE TITLE
Newer reviewers are missing

### ISSUE THREAD

**Issue by Minoru** [LucianoBestia/cargo_crev_web#22]
https://web.crev.dev/rust-reviews/reviewers/ only lists 64 reviewers, but it looks like there should be more:

```
$ cargo crev id query all | wc -l
94
```

As a second data point, I've been in auto-crev-proofs [for almost a week now](https://gitlab.com/crev-dev/auto-crev-proofs/-/commit/1781087adb2655f470fe8d35d3c3f7bcaa87ee38) (ignore `trust: medium` — that has been fixed), but I'm still missing from web.crev.dev.

Perhaps a cron job failed somewhere?

**Comment by LucianoBestia** [comment]
I will check it now. Thanks.
There is a lot of users that install crev and create a repository, but then never add a single review. I blocklist those until something changes.

**Comment by Minoru** [comment]
Ah, got it! My repo, https://github.com/Minoru/crev-proofs, is not in this list, so probably something else is going on.

**Comment by LucianoBestia** [comment]
I can find you: 
in number 15 of https://web.crev.dev/rust-reviews/reviewers/

**Comment by LucianoBestia** [comment]
It looks that upper-case first character are sorted before lower-case. Sorry for that. I will try to correct that. Thanks to pointing that. I appreciate.

**Comment by Minoru** [comment]
I wonder how I managed to miss myself there >_< Probably ".git" confused me. I should've just used page search in the browser… Thank you, @LucianoBestia!
