### ISSUE TITLE
add cargo_crev_web to "spread this info"

### ISSUE THREAD

**Issue by LucianoBestia** [LucianoBestia/cargo_crev_web#9]
@dpc, what do you think to put this text for "Raise awareness" on 
https://github.com/crev-dev/cargo-crev?

## Raise awareness - cargo crev reviews and advisory

It is recommended to always use [cargo-crev](https://github.com/crev-dev/cargo-crev)
to verify the trustworthiness of each of your dependencies, including this one.
`Please, spread this info !`
Use this url to read more crate reviews,  example:
https://web.crev.dev/cargo_crev_web/crate/num-traits

**Comment by dpc** [comment]
I think it would be better to switch to badges. They are less intrusive and have better appeal.
